module.exports = {
	Stats: require('./stats'),
	Warnum: require('./warnum'),
	Test: require('./test'),
	Hist: require('./hist'),
	Xp: require('./xp'),
	Post: require('./post'),
	Help: require('./help'),
	Mastery: require('./mastery'),
	Roles: require('./roles'),
	Pf: require('./pf'),
	// Apply: require('./apply'),
	// Archive: require('./archive'),
	// Top: require('./top'),
};
