module.exports = {
	Contract: require('./contract'),
	Help: require('./help'),
	Hist: require('./hist'),
	kpm: require('./kpm'),
	Link: require('./link'),
	Mastery: require('./mastery'),
	Pf: require('./pf'),
	// Post: require('./post'),
	Roles: require('./roles'),
	Stats: require('./stats'),
	Test: require('./test'),
	Warnum: require('./warnum'),
	Wars: require('./wars'),
	Xp: require('./xp'),
};
